name: Deploy Medusa Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      run: |
        docker build -t medusa-backend .
        docker tag medusa-backend:latest <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/medusa-backend:latest
        docker push <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/medusa-backend:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster medusa-cluster --service medusa-service --force-new-deployment
